public/changelog.html
Btw i made a class cuz i didnt wanna ruin ur code and stuff if i did- orca
i love you
=> Not spacing

public/changelog.html
=> Added the good stuff. The top and stuff

public/assets/css/settings/main.css
=> this might work

public/math.html, public/play.html, public/search.html, public/settings.html, public/widgetbot.html
the non-home pages have a widgetbot button that did not work, I made it work.
=> makes the widgetbot button work

public/apps.html
the button to send you to widgetbot was broken on apps page. this fixes it
=> fixes widgetbot redirect on apps page

README.md
=> minor grammatical error

public/apps.html, public/index.html, public/math.html
=> awsome visual bug glitches and makes navigation bar the same from page to page

README.md
=> another grammatical error

README.md
it's that time of the week again
=> Grammatical errors.... again

public/play.html
web retro is duplicate of Retro Arch (its the same thing)
=> Removed Duplicate Game

README.md
Made the contribution slightly better that way pfp's show. Also added some support and other things.
=> Readme fancy✨

README.md
Replit alert for how hosting is configured, that way unnecessary reports don't come in.
=> ReplitAlertReadMe

static/css/main.css
har har harhar ararhar aha rhar har
=> fix dumb backgorund bug custom when har har har repeats and zooms

static/scripts/enlighten.js
Adds the game. Closes game request #266.
=> Add Parappa The Rapper

README.md
I added a tutorial for running on GitHub Codespaces which would be very useful when Replit goes paid next year. 
Edit it to your liking.
=> Added Codespace tutorial 

static/go.html, static/tabs.html
Simple one-liner for allowing short presses of the escape key. This was made to fix a problem reported by @flodous on Discord.
May require some tweaking, PR is meant to serve as a base for a larger solution.
=> Allowing ESC while in fullscreen (for cloud gaming)

static/assets/scripts/home.js
1. This should make it faster
2. I used Google Classroom because [of this](https://discord.com/channels/938658733788131399/939603411366731807/1165413293612085289).
=> Redo iframe opening

README.md
...to avoid confusion when someone makes a link this month and then asks why it's not working or something.
=> Removed instructions for replit deployment.

app.json
=>  make heroku compatible with IN

.gitignore, static/assets/scripts/global.js, static/assets/styles/theme/catppuccin/frappe.css, static/assets/styles/theme/catppuccin/latte.css, static/assets/styles/theme/catppuccin/macchiato.css, static/assets/styles/theme/catppuccin/mocha.css, static/settings.html
=> Catppuccin themes

package.json
=> remove UV dep

package.json
=> Update Prettier to v3.2.4

package.json
Update Prettier version to 3.2.5
=> Update Pettier Version to 3.2.5

static/assets/styles/frame.css, static/go.html
To fix TGT's awful design choices. Also could I have push access to the repo? Would be useful.
=> Overhauled Navbar, added searchbar.

README.md, package.json
pnpm is way faster than npm and is installed on codespaces
=> pnpm for codespaces and fix bareserver vuln

static/settings.html
Fixed most, if not all, grammatical errors in settings.html
=> Fixed grammar in settings.html

static/assets/scripts/m.js, static/assets/scripts/s.js, static/settings.html
Adds option in settings to:
Create theme,
Import theme,
Delete theme,
and Export the current theme files.
Create theme adds a theme based on what you name it to the theme options list in the Themes! tab. The theme doesn't have anything until you use the import theme option.
Import theme takes a css file from you computer and assigns the css to the current theme.
Delete theme removes the theme and the css.
Export theme exports the css file.
Also implements fixes by Incognito from [here](https://github.com/UseInterstellar/Interstellar/pull/755)
=> Add custom themes

static/assets/scripts/s.js
fixes custom themes being created with a "," always, which causes them to not show at all.
=> fixes for the fixes

static/assets/scripts/s.js
Fix adding a theme with no characters, so "", would result in that being stuck there.
and fix themes not showing in a **VERY** specfic circumstances (having more then 1)
it turns out I may be a idiot sometimes, (last one I (dont) promise)
=> fix some more stuff

static/404.html, static/apps.html, static/assets/js/c.js, static/assets/js/i.js, static/assets/js/mv.js, static/assets/js/settings.js, static/games.html, static/index.html, static/settings.html, static/tabs.html
Crossorigin iframes prevent you from accessing the `location` property on the `top` or `parent`. This PR provides a fix that will attempt to access the `top`, then `parent`, then the current window.
Will fix the Interstellar IFrame bug report (DC)
=> Fix crossorigin iframes

README.md
people are incapable of reading
3 issues on gh codespaces with the same problem flagged in the readme?
closes #903
closes #907
closed #910
=> add extra line in codespaces section of readme

static/assets/js/t.js
youtube works a bit better once you add these flags
autoplay works and it throws less errors
probably closes #924
=> improve youtube support

.vscode/settings.json, index.js, static/assets/css/settings.css, static/assets/js/settings.js, static/settings.html
Adds a save data manager that can export your cookies and localStorage. Idea first pitched by @youraverageskeleton on discord, in [this thread](https://discord.com/channels/938658733788131399/1342899287088168970).
=> Save Data Manager

.vscode/settings.json, static/assets/js/settings.js, static/settings.html
The save data manager I created was only available for the main, or with ads branch of Interstellar. This PR adds the save data manager for the Ad-Free branch.
=> Finished save data manager for Ad-Free branch of Interstellar
